### ISSUE TITLE
Errors after upgade to AppDaemon3

### ISSUE THREAD

**Issue by vpomax** [runningman84/home-assistant-apps#2]
Hi, after upgrade from AppDaemon2 to Appdaemon3 in the AppDaemon3 log I found the following error...

```
2018-04-07 10:51:54.617550 WARNING AppDaemon: ------------------------------------------------------------
2018-04-07 10:51:54.618057 WARNING AppDaemon: Unexpected error running initialize() for alarm_system
2018-04-07 10:51:54.618623 WARNING AppDaemon: ------------------------------------------------------------
2018-04-07 10:51:54.620238 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1513, in init_object
    init()
  File "/config/appdaemon/apps/alarm.py", line 51, in initialize
    self.count_home_device_trackers(), self.count_not_home_device_trackers()))
  File "/config/appdaemon/apps/alarm.py", line 132, in count_home_device_trackers
    return self.count_device_trackers("home")
  File "/config/appdaemon/apps/alarm.py", line 127, in count_device_trackers
    if self.get_state(sensor) == state:
  File "/usr/lib/python3.6/site-packages/appdaemon/appapi.py", line 214, in get_state
    return self.AD.get_state(namespace, device, entity, attribute)
  File "/usr/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 644, in get_state
    return deepcopy(self.state[namespace])
KeyError: 'device_tracker.samsung_s8_wifi'
2018-04-07 10:51:54.620816 WARNING AppDaemon: ------------------------------------------------------------
```

**Comment by runningman84** [comment]
yes there were some changes. I will push my latest changes later this month. This will include v3 support and telegram notifications...

**Comment by runningman84** [comment]
This is my alarm.py with v3 support:
https://github.com/runningman84/home-assistant-apps/commit/5ca868360e27dc745b995e4b6bc52e5517a6acc8
Please test it and report any errors...

**Comment by vpomax** [comment]
Thank you Philipp, you made a great work.
I just tested your new version and it now works fine with Appdaemon v. 3.
I will happy if sometimes you will upgrade your script with new functions.
I'm looking to use a new mode to arm and disarm it via RFID using low cost device like RC522 and Nodemcu or D1 mini ESP8266 integrated with Home Assistant via MQTT... could be it interesting?

**Comment by runningman84** [comment]
Hmm I do not have these devices. I would be happy to accept some pull request if you want to implement it...

**Comment by vpomax** [comment]
These seem nice projects  easily adaptable to your system alarm... 
https://community.home-assistant.io/t/diy-poor-mans-alarm-control-panel/23930/6?u=vpomax
https://community.home-assistant.io/t/controlling-house-alarm-from-ha/67/19?u=vpomax
